sudo: false
language: php
os:
  - linux
php:
  - 7.3
before_script:
  - composer self-update
  - composer install --prefer-dist
  - touch .env.local
script: vendor/bin/phpunit
notifications:
  email: false
