language: php
os:
  - linux
php:
  - 8.0
  - nightly
jobs:
  allow_failures:
  - php: nightly
before_script:
  - test -f .env || cat .env.* > .env
  - make install
script: composer run-script test
notifications:
  email: false
