sudo: false
language: php
os:
  - linux
php:
  - 7.4
before_script:
  - make build
  - composer self-update
  - composer install --prefer-dist
  - touch .env.local
script: composer run-script test
notifications:
  email: false
