version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:symfony-dev-${TAG_VERSION}
        volumes:
            - $PWD/:/var/www/app
        networks:
            - backend
    mariadb:
        image: mariadb
        restart: always
        expose:
          - 3306
        environment:
          MYSQL_ROOT_PASSWORD: mas7er
          MYSQL_USER: app_db_user
          MYSQL_PASSWORD: app8as3
          MYSQL_DATABASE: app
        networks:
          - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mariadb
        expose:
          - 80
        restart: always
        env_file:
            - config/phpmyadmin.env
        networks:
            - backend
            - default
networks:
    default:
        external:
            name: nginx-proxy
    backend:
        external:
            name: localhost-backend
