version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:php-dev-${TAG_VERSION}
        env_file:
            - .env
            - .env.local
        volumes:
            - $PWD/:/var/www/app
        links:
          - db-service
        networks:
            - backend
    db-service:
        image: mariadb
        restart: always
        env_file:
            - .env
            - .env.local
        volumes:
            - $PWD/Resources/sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        expose:
          - 3306
        networks:
          - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - db-service
        expose:
          - 80
        restart: always
        env_file:
            - .env
            - .env.local
            - config/phpmyadmin.env
        networks:
            - backend
            - default
networks:
    default:
        external:
            name: nginx-proxy
    backend:
        external:
            name: localhost-backend
