<?php

declare(strict_types=1);

/*
 * This Test file is autogenerated at 02/04/2019 5:34pm by gpupo/common-sdk
 * @see <https://opensource.gpupo.com/common-sdk/>
 */

namespace Gpupo\BrazilianCars\Tests\Entity;


use PHPUnit\Framework\TestCase as CoreTestCase;
use Gpupo\Common\Entity\Collection;
use Gpupo\Common\Entity\CollectionInterface;
use Gpupo\BrazilianCars\Entity\VehicleManager;

class VehicleManagerTest extends CoreTestCase
{
    public function testExplodeData()
    {
        $vehicleManager = new vehicleManager();
        $brand = new Collection([
            'name' => 'Citroën',
        ]);
        $model = new Collection([
            'id'    => '2841',
            'name' => 'Berlingo MultSpace GLX 1.8i 3p',
        ]);
        $version = [
            'id' => '2841998-1',
            'name' => '1998 Gasolina'
        ];

        $vehicle = $vehicleManager->createVehicle($brand, $model, $version);
        $this->assertSame('Berlingo', $vehicle->getFamily());
        $this->assertSame('Gasolina', $vehicle->getFuelType());
    }

}
